CORE = parmk3

VSRC = address.v cheat.v clk_test.v dac.v dcm.v bsx.v rtc.v srtc.v main.v mcu_cmd.v msu.v sd_dma.v spi.v \
       parmk3_top.v parmk3_mapper.v parmk3_io.v parmk3_intercept.v parmk3_nmi_hook.v parmk3_fsm.v parmk3_pad_snoop.v
VHSRC =

COMMON_IP = dac_buf msu_databuf snescmd_buf

HEADER = config.vh

XIL_IP =
XIL_IPCORE_DIR = ipcore_dir

INT_IP = pll

include ../settings.mk
include ../common.mk
